#################################
#### OneBlock by The12Forest ####
#################################


Max_Level: 28 # Just provide the Maximum level.

'1':
  level-name: "Level: 1 - Podzol & melon"
  progress-bar-color: GREEN
  level-size: 20
  blocks:
    - PODZOL
    - GRASS_BLOCK
    - MELON
  mobs:
    - ZOMBIE
    - SPIDER

'2':
  level-name: "Level: 2 - Forest"
  progress-bar-color: GREEN
  level-size: 50
  blocks:
    - BIRCH_LOG
    - OAK_LOG
    - OAK_LEAVES
    - DIRT
    - GRASS_BLOCK
  mobs:
    - SHEEP
    - COW
    - PIG
    - CHICKEN

'3':
  level-name: "Level: 3 - Little cave"
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - STONE
    - COBBLESTONE
    - COAL_ORE
    - GRAVEL
  mobs:
    - SKELETON

'4':
  level-name: "Level: 4 - Deposits of rocky rocks"
  progress-bar-color: GREEN
  level-size: 40
  blocks:
    - GRANITE
    - DIORITE
    - ANDESITE
    - OAK_LOG
  mobs: []

'5':
  level-name: "Level: 5 - Little desert"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - SAND
    - SANDSTONE
    - CACTUS
  mobs: []

'6':
  level-name: "Level: 6 - Ore deposit"
  progress-bar-color: GREEN
  level-size: 100
  blocks:
    - IRON_ORE
    - COARSE_DIRT
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - GRANITE
    - DIORITE
    - ANDESITE
    - STONE
    - COBBLESTONE
    - OAK_LOG
  mobs: []

'7':
  level-name: "Level: 7 - The first chest"
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - MOSSY_COBBLESTONE
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - YELLOW_TERRACOTTA
  mobs:
    - HORSE
    - MULE
    - DONKEY

'8':
  level-name: "Level: 8 - Deep forest"
  progress-bar-color: GREEN
  level-size: 100
  blocks:
    - SPRUCE_LOG
    - DARK_OAK_LOG
    - SPRUCE_LEAVES
    - DIRT
    - GRASS_BLOCK
  mobs: []

'9':
  level-name: "Level: 9 - Mine"
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - STONE
    - COAL_ORE
    - GOLD_ORE
    - LAPIS_ORE
  mobs: []

'10':
  level-name: "Level: 10 - Snow?"
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - IRON_ORE
    - INFESTED_STONE
    - SNOW_BLOCK
    - PACKED_ICE
    - SPRUCE_LOG
    - DIRT
    - GRASS_BLOCK
  mobs: []

'11':
  level-name: "Level: 11 - Red desert?"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - CLAY
    - WHITE_CONCRETE
    - RED_SAND
    - RED_SANDSTONE
  mobs:
    - VILLAGER

'12':
  level-name: "Level: 12 - Acacia & mushrooms"
  progress-bar-color: GREEN
  level-size: 90
  blocks:
    - ACACIA_LOG
    - ACACIA_LEAVES
    - MUSHROOM_STEM
    - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - PUMPKIN
    - DIRT
    - GRASS_BLOCK
  mobs:
    - MUSHROOM_COW

'13':
  level-name: "Level: 13 - Sea"
  progress-bar-color: GREEN
  level-size: 50
  blocks:
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - SEA_LANTERN
    - OAK_LOG
    - DIRT
  mobs:
    - GUARDIAN
    - ELDER_GUARDIAN

'14':
  level-name: "Level: 14 - Am I rich?"
  progress-bar-color: GREEN
  level-size: 16
  blocks:
    - DIAMOND_ORE
    - EMERALD_ORE
    - CHISELED_SANDSTONE
  mobs: []

'15':
  level-name: "Level: 15 - Mangrove swamp"
  progress-bar-color: GREEN
  level-size: 50
  blocks:
    - MANGROVE_LEAVES
    - Mangrove_Log
    - Mangrove_Planks
    - Muddy_Mangrove_Roots
    - Stripped_Mangrove_Log
    - Bee_Nest
    - Mud
    - Clay
  mobs: []

'16':
  level-name: "Level: 16 - Obs..."
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - CUT_SANDSTONE
    - CARVED_PUMPKIN
    - OBSIDIAN
    - OAK_LO
    - DIRT
  mobs: []

'17':
  level-name: "Level: 17 - Hell!?"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - NETHERRACK
    - GLOWSTONE
    - SOUL_SAND
    - CRIMSON_STEM
  mobs:
    - PILLAGER
    - ZOMBIFIED_PIGLIN

'18':
  level-name: "Level: 18 - Deep Dark"
  progress-bar-color: GREEN
  level-size: 16
  blocks:
    - Sculk
    - Sculk_Sensor
    - Sculk_Catalyst
    - Sculk_Shrieker
  mobs:
    - WITHER_SKELETON
    - BLAZE
    - ZOGLIN
    - STRIDER

'19':
  level-name: "Level: 19 - Infernal terracotta?"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - CHISELED_STONE_BRICKS
    - NETHER_BRICKS
    - GREEN_TERRACOTTA
    - PINK_TERRACOTTA
    - NETHER_QUARTZ_ORE
    - BLACK_TERRACOTTA
    - WARPED STEM
    - STONE
    - COBBLESTONE
  mobs:
    - PIGLIN
    - HOGLIN

'20':
  level-name: "Level: 20 - Is that quartz?"
  progress-bar-color: GREEN
  level-size: 40
  blocks:
    - NETHER_BRICKS
    - NETHERRACK
    - NETHER_QUARTZ_ORE
  mobs: []

'21':
  level-name: "Level: 21 - Never mine..."
  progress-bar-color: GREEN
  level-size: 20
  blocks:
    - PRISMARINE
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - AMETHYST_BLOCK
  mobs: []

'22':
  level-name: "Level: 22 - Never..."
  progress-bar-color: GREEN
  level-size: 40
  blocks:
    - NETHERRACK
    - CRIMSON_STEM
  mobs:
    - high_chest

'23':
  level-name: "Level: 23 - Ne..."
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - WARPED_STEM
    - OXIDIZED_COPPER
    - NETHER_GOLD_ORE
    - DEEPSLATE
    - CHISELED_DEEPSLATE
  mobs:
    - high_chest

'24':
  level-name: "Level: 24 - Ancient City"
  progress-bar-color: GREEN
  level-size: 80
  blocks:
    - Deepslate
    - Cobbled_Deepslate
    - Polished_Deepslate
    - Deepslate_Bricks
    - Deepslate_Tiles
    - Chiseled_Deepslate
    - Deepslate_Bricks
    - Gray_Wool
    - Sculk_Sensor
    - Redstone_Lamp
    - Soul_Sand
    - Furnace
    - Lectern
    - REDSTONE_BLOCK
    - Target
    - DIRT
    - GRASS_BLOCK
  mobs: []

'25':
  level-name: "Level: 25"
  progress-bar-color: GREEN
  level-size: 20
  blocks:
    - CRIMSON_HYPHAE
    - WARPED_HYPHAE
    - CRACKED_NETHER_BRICKS
  mobs: []

'26':
  level-name: "Level: 26 - Deep crying"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - SHROOMLIGHT
    - CRYING_OBSIDIAN
    - BLACKSTONE
    - DEEPSLATE_BRICKS
    - CRACKED_DEEPSLATE_BRICKS
    - WARPED STEM
    - DIRT
  mobs: []

'27':
  level-name: "Level: 27"
  progress-bar-color: GREEN
  level-size: 90
  blocks:
    - ANCIENT_DEBRIS
    - POLISHED_BLACKSTONE
    - NETHERRACK
    - BLACKSTONE
    - NETHER_BRICKS
    - GRAVEL
    - SOUL_SAND
    - GLOWSTONE
    - CHISELED_POLISHED_BLACKSTONE
    - BLACKSTONE_BRICKS
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
  mobs: []

'28':
  level-name: "Level: 28 - The end?"
  progress-bar-color: GREEN
  level-size: 32
  blocks:
    - END_STONE
    - CUT_SANDSTONE
    - CARVED_PUMPKIN
    - OBSIDIAN
    - PUMPKIN
  mobs: []

'0':
  level-name: "Infinity"
  progress-bar-color: GREEN
  level-size: 64
  blocks:
    - GRASS_BLOCK
    - PODZOL
    - BIRCH_LOG
    - OAK_LOG
    - OAK_LEAVES
    - STONE
    - COBBLESTONE
    - COAL_ORE
    - GRAVEL
    - GRANITE
    - DIORITE
    - ANDESITE
    - SAND
    - SANDSTONE
    - CACTUS
    - IRON_ORE
    - COARSE_DIRT
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - MOSSY_COBBLESTONE
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - SPRUCE_LOG
    - DARK_OAK_LOG
    - SPRUCE_LEAVES
    - GOLD_ORE
    - LAPIS_ORE
    - INFESTED_STONE
    - SNOW_BLOCK
    - PACKED_ICE
    - CLAY
    - WHITE_CONCRETE
    - RED_SAND
    - RED_SANDSTONE
    - ACACIA_LOG
    - ACACIA_LEAVES
    - MUSHROOM_STEM
    - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - PUMPKIN
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - SEA_LANTERN
    - DIAMOND_ORE
    - EMERALD_ORE
    - CHISELED_SANDSTONE
    - MANGROVE_LEAVES
    - Mangrove_Log
    - Mangrove_Planks
    - Muddy_Mangrove_Roots
    - Stripped_Mangrove_Log
    - Bee_Nest
    - Mud
    - CUT_SANDSTONE
    - CARVED_PUMPKIN
    - OBSIDIAN
    - NETHERRACK
    - GLOWSTONE
    - SOUL_SAND
    - Sculk
    - Sculk_Sensor
    - Sculk_Catalyst
    - Sculk_Shrieker
    - CHISELED_STONE_BRICKS
    - NETHER_BRICKS
    - GREEN_TERRACOTTA
    - PINK_TERRACOTTA
    - NETHER_QUARTZ_ORE
    - BLACK_TERRACOTTA
    - PRISMARINE
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - AMETHYST_BLOCK
    - DIAMOND_BLOCK
    - CRIMSON_STEM
    - WARPED_STEM
    - OXIDIZED_COPPER
    - NETHER_GOLD_ORE
    - Deepslate
    - Cobbled_Deepslate
    - Polished_Deepslate
    - Deepslate_Bricks
    - Deepslate_Tiles
    - Chiseled_Deepslate
    - Gray_Wool
    - Redstone_Lamp
    - Furnace
    - Lectern
    - REDSTONE_BLOCK
    - Target
    - CRIMSON_HYPHAE
    - WARPED_HYPHAE
    - CRACKED_NETHER_BRICKS
    - SHROOMLIGHT
    - CRYING_OBSIDIAN
    - BLACKSTONE
    - DEEPSLATE_BRICKS
    - CRACKED_DEEPSLATE_BRICKS
    - NETHERITE_BLOCK
    - ANCIENT_DEBRIS
    - POLISHED_BLACKSTONE
    - END_STONE
  mobs: []
